### PR TITLE
fix: examples

### PR DESCRIPTION
**Pull request by FleetAdmiralJakob**
Until these issues: https://github.com/FormidableLabs/react-live/issues/404, https://github.com/FormidableLabs/react-live/issues/403 are fixed in react-live here are some simple fixes to these annoying SyntaxErrors:
image

### CODE REVIEW

**Comment by childrentime** [comment]
Wow, I'm very surprised. I don't know which version suddenly had this issue.

**Comment by childrentime** [comment]
Maybe it was when I upgraded Docusaurus previously - I didn't expect this issue would occur.

**Comment by childrentime** [comment]
Thanks very much!!!

**Comment by FleetAdmiralJakob** [comment]
> Maybe it was when I upgraded Docusaurus previously - I didn't expect this issue would occur.

Maybe important to mention that our react-live version is not the latest one but if I look in the changelog it doesnt seem like it adresses our issue

**Comment by childrentime** [comment]
The version of react-live shouldn't matter - it was added during my previous debugging but isn't actually being used. The real usage of react-live comes from @docusaurus/theme-live-codeblock - you should check the react-live version in that package.

**Comment by childrentime** [comment]
That's interesting - I discovered that this package is also using react-live 4.1.7, and coincidentally, that update to react-live was from my previous commit: https://github.com/FormidableLabs/react-live/issues/389

**Comment by childrentime** [comment]
Anyway, it's strange that their own website works fine with no issues. 
image

**Pull request merged**
