### PR TITLE
fix: esm import error

### PR DESCRIPTION
**Pull request by childrentime**
fix this

```error
import { isEqual, throttle, debounce } from 'lodash';
                            ^^^^^^^^
SyntaxError: Named export 'debounce' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { isEqual, throttle, debounce } = pkg;

``

### CODE REVIEW

**Comment by Daydreamer-riri** [comment]
This approach will result in the full import of lodash, making it impossible to load on demand.
Perhaps we can consider using `lodash-es`?

**Comment by childrentime** [comment]
Yes, you're right. I will try this, hope it can work in commonjs too.

**Comment by childrentime** [comment]
It seems link the build assets can both work on commonjs(create-react-app) and esm(nextjs). The only problem is it will broke jest test.

**Comment by childrentime** [comment]
@Daydreamer-riri help rereview it.

**Review by Daydreamer-riri — APPROVED** [review]
great！

**Pull request merged**
