### PR TITLE
fix: optimize usePrevious

### PR DESCRIPTION
**Pull request by FleetAdmiralJakob**
My personal solution to: #115 

Greetings from Australia btw. (I live in a similar timezone hehe)

### CODE REVIEW

**Review by childrentime — APPROVED** [review]
LGTM👍

**Comment by FleetAdmiralJakob** [comment]
> haha. so it is night 2am🤯?

🤣

**Comment by FleetAdmiralJakob** [comment]
> haha. so it is night 2am🤯?

Actually its already 3am

**Comment by childrentime** [comment]
too strong!

**Pull request merged**
