### PR TITLE
chore: add packageManager field for github action

### PR DESCRIPTION
**Pull request by Daydreamer-riri**

### CODE REVIEW

**Comment by childrentime** [comment]
Thanks, I just fixed this. Thank you for your great work😘! I think I should also use pull request to submit the code later.

**Comment by childrentime** [comment]
just open branch protected.

**Comment by childrentime** [comment]
https://github.com/childrentime/reactuse/invitations would you linke to be a collaborator？

**Comment by Daydreamer-riri** [comment]
sure，I am very willing.

**Pull request closed without merging**
