### PR TITLE
feat(core): useMediaDevices: support request permission

### LINKED ISSUE #40: Feature Request: Some way to refresh device list of `useMediaDevices`
While working with some webcam flows in React, I've found that permissions states can be really funky in browsers. Specifically, when first requesting permissions, you don't have access to the proper input device list until the user has granted permissions. Once the user _does_ grant permissions, it doesn't seem to automatically re-trigger the `useMediaDevices` hook, since that's not directly tied to any permission change events (and can't effectively be since Firefox doesn't support `camera`/`microphone` as permissions in the permissions API).

My proposal:

Some sort of optional function that can be used to manually trigger an update on the useMediaDevices check, i.e.

```ts
const { devices, reload: reloadDeviceList } = useMediaDevices();
...
navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then((stream) => {
      stream.getTracks().forEach((track) => track.stop());
      reloadDeviceList();
    })
```

### PR DESCRIPTION
**Pull request by childrentime**
fix #40

### CODE REVIEW

**Comment by Daydreamer-riri** [comment]
Sorry I'm so late checking my github notifications

**Comment by childrentime** [comment]
It's OK. Just have fun

**Comment by childrentime** [comment]
As a PDDer, I totally understand how busy can work get. I just happen to have more free time recently, so if you're busy, you don't need to care about it. Just check it when you want to, this is not work🥰

**Comment by Daydreamer-riri** [comment]
Our two companies don't seem to be far apart.🥳

**Pull request merged**
