### PR TITLE
Fix Eslint, add vscode setting and remove property

### PR DESCRIPTION
**Pull request by childrentime**
Hi.

1. First of all, I think we use eslint to validate code in `core` is enough now. we dont't need validate all code. And I add some vscode configuration to auto save.
2. Second, it seems `pnpm` property in `core package.json` in invalid, we only need it in root `package.json`

### CODE REVIEW

**Review by Daydreamer-riri — CHANGES_REQUESTED** [review]
```json
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "eslint-plugin-react": "^7.31.5",
```
These three packages have already been depended on in `@ririd/eslint-config`, so we don't need to depend on them again. We can remove them.

**Review by Daydreamer-riri — DISMISSED** [review]

**Review by Daydreamer-riri — APPROVED** [review]

**Review by Daydreamer-riri — APPROVED** [review]

**Comment by Daydreamer-riri** [comment]
Sorry, it seems that some of my actions have prevented me from merging this PR. Can you please resubmit a new PR?

**Review by Daydreamer-riri — APPROVED** [review]

**Comment by childrentime** [comment]
> ```json
>     "@typescript-eslint/eslint-plugin": "^5.36.1",
>     "@typescript-eslint/parser": "^5.36.1",
>     "eslint-plugin-react": "^7.31.5",
> ```
> 
> These three packages have already been depended on in `@ririd/eslint-config`, so we don't need to depend on them again. We can remove them.

sorry forget this

**Comment by childrentime** [comment]
Due to setup reasons, you should not be able to self-review when you push code.

**Comment by Daydreamer-riri** [comment]
sure

**Comment by childrentime** [comment]
Later I will remove the excess dependencies and add a new hook in the new PR

**Pull request merged**
