### PR TITLE
chore(core): remove ghost dependency

### PR DESCRIPTION
**Pull request by Daydreamer-riri**
image

@jest/types does not exist in package.json and should not be imported.

### CODE REVIEW

**Review by childrentime — APPROVED** [review]

**Comment by childrentime** [comment]
merged

**Comment by childrentime** [comment]
I don't seem to have this hint. Is there any vscode plugin or eslint special configuration？

**Comment by Daydreamer-riri** [comment]
Because the shamefully-hoist in npmrc is set to true, it hoists all dependencies even if they are not direct dependencies of the project itself.

I think it should be set to false.

**Comment by Daydreamer-riri** [comment]
You can learn about it from the [pnpm documentation](https://pnpm.io/npmrc#shamefully-hoist)

**Pull request merged**
